package dev.javiermarro.films;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Document(collection = "reviews")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Review {

    @Id
    private ObjectId id;
    private String body;

    // ids are auto generated so we wouldn't be able to pass it to the class
    // annotations above create a constructor with all arguments available AND with no arguments
    // we need a custom constructor that only takes the body field property

    // this can be autogenerated by IntelliJ by:
    // right click, generate -> constructor -> choose field
    public Review(String body) {
        this.body = body;
    }
}
